### ISSUE TITLE
How to install `perf`?

### ISSUE THREAD

**Issue by kwhkim** [PracticalTimeSeriesAnalysis/BookRepo#7]
In chapter 10, there is `import perf` but I can't figure out how to install this

`pip install perf` does not install the adequate package...

**Comment by mjonkus** [comment]
What was the solution? Looking at the same issue :)

**Comment by ggguys-master** [comment]
@kwhkim @mjonkus 
hi, I am facing this problem too. If you have found any solution to this problem, I would love to know!
The environment is google colab and the pip version is up to date.
